### PR TITLE
Fixed black death wrapper

### LINKED ISSUE #133: Black_death makes battle return supicious rewards
Done with supersuit==3.3.3, pettingzoo==1.15.0 and magent==0.1.14

I am conducting some experiments with MAgent environments. I am starting with work on Battle using minimap_mode (for access to the coordinates).

I tried using black_death for easier death handling (mainly for not needing to care which action a dead agent gets), but get some weird rewards. 

The following minimal code example:
```
from pettingzoo.magent import battle_v3
import supersuit as ss

max_cycles = 50000
env = battle_v3.parallel_env(map_size=30, minimap_mode=True, max_cycles=max_cycles, extra_features=False)
env = ss.black_death_v2(env)
env.reset()
handles = env.agents

for k in range(max_cycles):

    action_dict = {name : env.action_space(name).sample() for name in handles}
    _, rewards, _, _ = env.step(action_dict)

    if max(rewards.values()) > 20:
        print("problematic reward", max(rewards.values()))
```

provides me with the following output:

```
problematic reward 171.32499933242798
problematic reward 239.85499906539917
problematic reward 132.16499948501587
problematic reward 288.8049988746643
```

Is there something I did wrong or is it actually a bug? A similar issue was mentioned as fixed in some older release.

### PR DESCRIPTION
**Pull request by benblack769**
Resolves #133

### CODE REVIEW

**Comment by RedTachyon** [comment]
So apparently here be dragons. 

As I understand, this is a total remake of the black death wrapper, yes? (basically meaning that whatever diff is irrelevant, and it should be analyzed in isolation from the previous version)

I can't actually test it right now, but from a cursory glance over the code, here are some potential pitfalls:
0. L8 checks whether the env has `env.possible_agents`, but then the wrapper doesn't use that. Maybe it should be used in place of `self.env.agents` in L23? This would support agents who die and who have yet to be spawned, if at all.
0. Info will have an empty dictionary for each "dead" agent - is this the standard PZ convention? (I'm not sure)
0. Episode ends when all agents end - I assume this is intended

Are there any specific reasons why you're suspicious of this code?

**Comment by benblack769** [comment]
@RedTachyon This is the problem: #133 .

**Comment by benblack769** [comment]
Overall, this rewrite should be very similar to the old environment, but without the bug. But I don't want to waste time pawing through that old code.

I've spent way too much time looking at that old code, and I don't want people to spend time reasoning about crazy edge cases there, especially if it doesn't work, especially if all the use cases for this wrapper are parallelizable environments anyways, hence the rewrite.

1. Good point about possible_agents. I think I changed my mind half way through this implementation. Changed to check the  observation spaces on reset.
2. There is no convention for dead agents. If there is any, this is the place to define the convention. We are open to suggestions, if you have any. Right now, the only way to check if the agent is dead is to check if the observation is all 0, which may be a bit dubious for some environments.
3. Yes, this is the idea.

**Comment by RedTachyon** [comment]
#133 is with the previous version of the wrapper though, right? Or is the same issue present here?

I agree that the previous implementation was... tricky. But this seems to be pretty straight forward since we can skip all of the AEC stuff

**Comment by benblack769** [comment]
Yeah, that was with the previous implementation. There is no particular problem I know about the current implementation, other than the obvious history of problems.

**Pull request merged**
