### PR TITLE
WIP: Move seed to reset()

### PR DESCRIPTION
**Pull request by elbamos**
This is a WIP in support of a related PR on PettingZoo.  I expect this to fail tests since neither PettingZoo nor Gym has been updated to have the seed parameter on the reset function.

### CODE REVIEW

**Comment by benblack769** [comment]
I started looking at this, and the number of remaining changes requires here is significant. Especially the vector environments need to be rethought pretty thoroughly.

**Comment by benblack769** [comment]
Basically, we need to decide how this seed argument to reset operates in vector environments. I assume this will also have to align with however gym does it.

**Comment by benblack769** [comment]
Looks like the gym implementation is finished: https://github.com/openai/gym/blob/master/gym/vector/sync_vector_env.py#L89

**Comment by jjshoots** [comment]
Hi @elbamos, how's this PR going on?

**Comment by jjshoots** [comment]
Closing becuase #146 deals with this already

**Comment by elbamos** [comment]
I’m unlikely to have a chance to look at this soon - I’ve become pretty tied up.

**Comment by WillDudley** [comment]
This issue has been dealt with anyway as per the previous comment.

**Pull request closed without merging**
